### ISSUE TITLE
Set up monitoring

### ISSUE THREAD

**Issue by Eik-S** [tracemap/tracemap-backend#58]
## Research Results
I would suggest to use grafana because its free and fancy:
[get it here](https://grafana.com/get)

## Feature Checklist
Please create Feature branches on your way through the epic
- [x]  #77 set up monitoring frontend (grafana or other)
  - -> ELK Stack (ElasticSearch, Logstash, Kibana) 
- [ ] ~~#78 set up neo4j monitoring~~ (neo4j commercial license needed)
  - ~~db size, throughput, lock frequency~~
  - -> ~~[Prometheus Endpoint](https://neo4j.com/docs/operations-manual/current/monitoring/metrics/#metrics-prometheus) -> [MetricBeat](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-prometheus.html)~~
- [x] #79 set up twitterLogin monitoring (nodejs)
  - availability, monitor visits
  - availability: [HeartBeat](https://www.elastic.co/products/beats/heartbeat)
  - visits: logfile + [FileBeat](https://www.elastic.co/de/products/beats/filebeat)
- [x] #80 set up api monitoring
  - which routes are used how often ->  logfile + [FileBeat](https://www.elastic.co/de/products/beats/filebeat)
  - how long does each route take to process -> [PacketBeat](https://www.elastic.co/de/products/beats/packetbeat)
- [x] #81 set up crawler monitoring
  - refactor logging #76 
  - followers/sec ->  in-code measurement -> logfile -> [FileBeat](https://www.elastic.co/de/products/beats/filebeat)
  - token usage -> neo4j-query -> [FileBeat](https://www.elastic.co/de/products/beats/filebeat)
  - filesystem crawler-writer-queue -> shell-script -> [FileBeat](https://www.elastic.co/de/products/beats/filebeat)
- [x] #82 per host: PacketBeat, MetricBeat(System) (Netcup only)
- [ ] ~~#83 Alerting~~
