### ISSUE TITLE
Create pull request template

### ISSUE THREAD

**Issue by jonathanschlue** [tracemap/tracemap-backend#61]
## Description

We need a pull request template with a placeholder for auto closing issues.

## Progress checklist
- [x] Find good starting point for a template
- [x] Ensure Issues is auto closed.

**Comment by jonathanschlue** [comment]
Have a peek here:

![bildschirmfoto vom 2018-10-11 22-10-36](https://user-images.githubusercontent.com/15818147/46831027-c393de80-cd91-11e8-8c79-fe922ce657d8.png)

**Comment by jonathanschlue** [comment]
# TODO

- [ ] Add "Don't merge before" hint
