### ISSUE TITLE
Check security updates

### ISSUE THREAD

**Issue by jonathanschlue** [tracemap/tracemap-backend#75]
We need to review the github security warnings about `requriements.txt` and check current ssl certificates for all domains needed on backend. In detail, we need to verifiy cerbot is currently running and renewing all our certificates correctly.
 
## TODO

- [x] check `requirements.txt`
- [x] check certificates for all subdomains and domains on netcup
- [x] enable automatic certbot nginx certificate renewal
- [x] get ssl certificates for aws server neo4j instance
- [x] secure neo4j

## Comments

Wildcard certificates does not work with certbot-auto atm.  
Also installing an additional DNS plugin for certbot would be needed for automatic wildcard cert renewal via letsencrypt acme v2 api.  
See https://certbot.eff.org/lets-encrypt/ubuntubionic-nginx

 - https://letsencrypt.readthedocs.io/en/latest/intro.html
 - https://certbot.eff.org/lets-encrypt/ubuntubionic-nginx

**Comment by jonathanschlue** [comment]
also review cerbot automation
