### ISSUE TITLE
improve crawler writer interaction

### ISSUE THREAD

**Issue by Eik-S** [tracemap/tracemap-backend#84]
## Description
The Writer should not rely on a queue anymore.
The writer queue is atm blocking the crawlers if there are too many files in the `temp` folder. We should get rid of the writing queue so that the crawlers are just crawling as fast as they can.
As a second improvement, big users (1mil followers and more) should be written by their own crawler which is waiting if small priority 1 users need to be written to the database.
This can be realized by the python3 threading `lock()` object.

## Progress checklist

- [x] detach writers queue from crawlers
- [x] mark big users when crawlers save them (e.g. with a `big_` prefix
- [x] mark priority users when crawlers save them (e.g. with a `prio_` prefix
- [x] implement writer for just writing prio users
- [x] implement shared lock in the writer processes
  - lock if priority queue has users
  - normal writer is acquiring the lock before and releasing it after each database request to not block the priority writer of its queue is filled.

## Comments
The following naming should be used for all the crawled users in the `temp` folder:
**Prefixes:**
- `prio_` -> user has priority 1 (requested by some user from the frontend)
- `big_` -> user has more than 1mil followers
- `temp_` -> crawling of user is in progress and not finished yet
**Suffixes:**
- `_save.txt` -> user needs to be saved to the database
- `_delete.txt` -> user needs to be deleted from the database (corresponding twitter user is now private or deleted)

**Comment by brunopace** [comment]
I have had a meeting with Samir, and he suggested that the data should be streamed between crawlers and writer, using something like https://www.rabbitmq.com/. He thinks that writing to disk is slowing the whole process down.
